// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4C4az161BjP-PRPqt8gH_b_wEJMBn9L0',
    appId: '1:114100502482:web:00deb74d73ad069ed3d20b',
    messagingSenderId: '114100502482',
    projectId: 'ghyabko-377e0',
    authDomain: 'ghyabko-377e0.firebaseapp.com',
    storageBucket: 'ghyabko-377e0.appspot.com',
    measurementId: 'G-VL0BC25PKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAi3cR6GtJmWX-AxsQq6Vi4tgNPC2EDZs',
    appId: '1:114100502482:android:30e6830cd5d39d9ed3d20b',
    messagingSenderId: '114100502482',
    projectId: 'ghyabko-377e0',
    storageBucket: 'ghyabko-377e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOH7FXwKpOzubSanhzP72XQxCnf2Nu0CI',
    appId: '1:114100502482:ios:a701b6d967e08eefd3d20b',
    messagingSenderId: '114100502482',
    projectId: 'ghyabko-377e0',
    storageBucket: 'ghyabko-377e0.appspot.com',
    iosBundleId: 'com.example.ghyabko',
  );
}
